# Generated by Django 4.1.3 on 2022-11-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_name',
            field=models.CharField(max_length=255),
        ),
    ]
