# Generated by Django 4.1.3 on 2022-11-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_name',
            field=models.CharField(choices=[('PYTHON', 'PYTHON'), ('JAVA', 'JAVA')], max_length=255),
        ),
    ]
